# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAMv8UrGrnV0B7-4HaubN2df0JPoSFv7
"""



# -----------------------------------------
# TrendPulse — Task 2: Data Processing
# -----------------------------------------
# Loads JSON from Task 1, cleans the data,
# and saves it as a CSV file.

import pandas as pd
import os

# -----------------------------------------
# Step 1: Load JSON file (auto-detect)
# -----------------------------------------

data_folder = "data"

# Check if data folder exists
if not os.path.exists(data_folder):
    print("data/ folder not found. Run Task 1 first.")
    exit()

# Find JSON files
json_files = [f for f in os.listdir(data_folder) if f.endswith(".json")]

if not json_files:
    print("No JSON files found. Run Task 1 first.")
    exit()

# Pick latest file
latest_file = sorted(json_files)[-1]
file_path = os.path.join(data_folder, latest_file)

# Load JSON
df = pd.read_json(file_path)

print(f"Loaded {len(df)} stories from {file_path}")

# -----------------------------------------
# Step 2: Data Cleaning
# -----------------------------------------

# Remove duplicates
df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")

# Remove missing values
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# Remove low-quality stories (score < 5)
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# Convert data types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove extra whitespace in title
df["title"] = df["title"].str.strip()

# -----------------------------------------
# Step 3: Save as CSV
# -----------------------------------------

output_path = "data/trends_clean.csv"

df.to_csv(output_path, index=False)

print(f"\nSaved {len(df)} rows to {output_path}")

# -----------------------------------------
# Step 4: Summary
# -----------------------------------------

print("\nStories per category:")
print(df["category"].value_counts())

