# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAMv8UrGrnV0B7-4HaubN2df0JPoSFv7
"""

# -----------------------------------------
# TrendPulse — Task 3: Data Analysis
# -----------------------------------------
# Loads cleaned CSV, performs analysis using
# Pandas & NumPy, adds new columns, and saves result.

import pandas as pd
import numpy as np
import os

# -----------------------------------------
# Step 1: Load and Explore Data
# -----------------------------------------

file_path = "data/trends_clean.csv"

if not os.path.exists(file_path):
    print("CSV file not found. Run Task 2 first.")
    exit()

df = pd.read_csv(file_path)

print(f"Loaded data: {df.shape}")

# First 5 rows
print("\nFirst 5 rows:")
print(df.head())

# Average score and comments
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print(f"\nAverage score   : {avg_score:.2f}")
print(f"Average comments: {avg_comments:.2f}")

# -----------------------------------------
# Step 2: NumPy Analysis
# -----------------------------------------

scores = df["score"].to_numpy()
comments = df["num_comments"].to_numpy()

print("\n--- NumPy Stats ---")

print(f"Mean score   : {np.mean(scores):.2f}")
print(f"Median score : {np.median(scores):.2f}")
print(f"Std deviation: {np.std(scores):.2f}")

print(f"Max score    : {np.max(scores)}")
print(f"Min score    : {np.min(scores)}")

# Category with most stories
category_counts = df["category"].value_counts()
top_category = category_counts.idxmax()
top_count = category_counts.max()

print(f"\nMost stories in: {top_category} ({top_count} stories)")

# Most commented story
max_comments_idx = np.argmax(comments)
most_commented_title = df.iloc[max_comments_idx]["title"]
most_comments = comments[max_comments_idx]

print(f"\nMost commented story: \"{most_commented_title}\" — {most_comments} comments")

# -----------------------------------------
# Step 3: Add New Columns
# -----------------------------------------

# Engagement = comments per score
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular = score > average score
df["is_popular"] = df["score"] > avg_score

# -----------------------------------------
# Step 4: Save Result
# -----------------------------------------

output_path = "data/trends_analysed.csv"

df.to_csv(output_path, index=False)

print(f"\nSaved to {output_path}")



