# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f21-gGzNAkp1SQ_zOxSto2lKUo-XZnhX
"""

# -----------------------------------------
# TrendPulse — Task 2: Data Processing
# -----------------------------------------
# Loads JSON data from Task 1, cleans it,
# and saves a structured CSV file.

import pandas as pd
import os
from datetime import datetime

# -----------------------------------------
# Step 1: Locate latest JSON file
# -----------------------------------------

data_folder = "data"

# Get latest JSON file
files = [f for f in os.listdir(data_folder) if f.endswith(".json")]

if not files:
    print("No JSON files found. Run Task 1 first.")
    exit()

latest_file = sorted(files)[-1]
file_path = os.path.join(data_folder, latest_file)

print(f"Loading data from: {file_path}")

# -----------------------------------------
# Step 2: Load JSON into DataFrame
# -----------------------------------------

df = pd.read_json(file_path)

print(f"Initial records: {len(df)}")

# -----------------------------------------
# Step 3: Data Cleaning
# -----------------------------------------

# Remove duplicates based on post_id
df.drop_duplicates(subset="post_id", inplace=True)

# Handle missing values
df["title"] = df["title"].fillna("No Title")
df["author"] = df["author"].fillna("Unknown")
df["score"] = df["score"].fillna(0)
df["num_comments"] = df["num_comments"].fillna(0)

# Ensure correct data types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

print(f"Records after cleaning: {len(df)}")

# -----------------------------------------
# Step 4: Save as CSV
# -----------------------------------------

output_file = f"data/cleaned_trends_{datetime.now().strftime('%Y%m%d')}.csv"

df.to_csv(output_file, index=False)

print(f"Cleaned data saved to: {output_file}")