# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f21-gGzNAkp1SQ_zOxSto2lKUo-XZnhX
"""

# -----------------------------------------
# TrendPulse — Task 4: Data Visualization
# -----------------------------------------
# Creates visualizations from cleaned CSV data

import pandas as pd
import matplotlib.pyplot as plt
import os

# -----------------------------------------
# Step 1: Load latest CSV file
# -----------------------------------------

data_folder = "data"

files = [f for f in os.listdir(data_folder) if f.endswith(".csv")]

if not files:
    print("No CSV files found. Run Task 2 first.")
    exit()

latest_file = sorted(files)[-1]
file_path = os.path.join(data_folder, latest_file)

print(f"Loading data from: {file_path}")

df = pd.read_csv(file_path)

# -----------------------------------------
# Step 2: Category Distribution (Bar Chart)
# -----------------------------------------

category_counts = df["category"].value_counts()

plt.figure()
category_counts.plot(kind="bar")
plt.title("Number of Stories per Category")
plt.xlabel("Category")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# -----------------------------------------
# Step 3: Score Distribution (Histogram)
# -----------------------------------------

plt.figure()
df["score"].plot(kind="hist", bins=20)
plt.title("Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# -----------------------------------------
# Step 4: Comments Distribution (Histogram)
# -----------------------------------------

plt.figure()
df["num_comments"].plot(kind="hist", bins=20)
plt.title("Comments Distribution")
plt.xlabel("Number of Comments")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()