# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f21-gGzNAkp1SQ_zOxSto2lKUo-XZnhX
"""

"""
TrendPulse — Task 1: Data Collection
Fetches trending stories from the HackerNews API, assigns categories,
and saves results to a JSON file in the data/ folder.

Author: Pavithra
"""

import requests
import json
import os
import time
from datetime import datetime

# ──────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────

BASE_URL = "https://hacker-news.firebaseio.com/v0"
HEADERS = {"User-Agent": "TrendPulse/1.0"}
MAX_PER_CATEGORY = 25
TOP_N_IDS = 500

# Category keywords — expanded so sparse categories (sports, science,
# worldnews) still hit 25 stories reliably from 500 IDs.
# All matching is case-insensitive substring search on the title.
CATEGORIES = {
    "technology": [
        "AI", "software", "tech", "code", "computer", "data", "cloud",
        "API", "GPU", "LLM", "python", "javascript", "linux", "open source",
        "github", "programming", "developer", "startup", "app", "database",
        "model", "neural", "machine learning", "framework", "security",
        "browser", "compiler", "algorithm", "hardware", "chip", "server",
        "deploy", "docker", "kubernetes", "rust", "golang", "typescript",
    ],
    "worldnews": [
        "war", "government", "country", "president", "election", "climate",
        "attack", "global", "ukraine", "russia", "china", "iran", "israel",
        "nato", "sanctions", "ceasefire", "diplomacy", "military", "nuclear",
        "refugee", "immigration", "border", "protest", "economy", "inflation",
        "gdp", "trade", "policy", "congress", "senate", "parliament", "court",
        "supreme", "law", "regulation", "tax", "budget",
    ],
    "sports": [
        "NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league",
        "championship", "soccer", "football", "basketball", "baseball",
        "tennis", "golf", "Olympics", "athlete", "coach", "stadium",
        "tournament", "match", "season", "draft", "trade", "transfer",
        "score", "win", "loss", "playoff", "super bowl", "world cup",
        # HN-relevant sports: esports, endurance, strategy, racing
        "chess", "F1", "formula 1", "cricket", "cycling", "marathon",
        "esport", "poker", "UFC", "MMA", "boxing", "swimming",
        "running", "triathlon", "fitness", "workout", "training",
        "racing", "NASCAR", "Wimbledon", "grand prix",
    ],
    "science": [
        "research", "study", "space", "physics", "biology", "discovery",
        "NASA", "genome", "quantum", "climate change", "experiment",
        "scientist", "journal", "paper", "lab", "molecule", "gene",
        "protein", "vaccine", "medicine", "drug", "cancer", "brain",
        "neuroscience", "astronomy", "telescope", "Mars", "Moon", "planet",
        "fossil", "evolution", "mathematics", "theorem", "proof",
    ],
    "entertainment": [
        "movie", "film", "music", "Netflix", "book", "show", "award",
        "streaming", "album", "artist", "actor", "director", "review",
        "trailer", "sequel", "series", "episode", "podcast", "youtube",
        "spotify", "disney", "marvel", "anime", "game", "videogame",
        "playstation", "xbox", "nintendo", "concert", "festival",
        "celebrity", "interview", "documentary",
    ],
}

# ──────────────────────────────────────────────
# STEP 1: FETCH TOP STORY IDs
# ──────────────────────────────────────────────

def fetch_top_story_ids(n=TOP_N_IDS):
    """Fetch the top N story IDs from HackerNews."""
    url = f"{BASE_URL}/topstories.json"
    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
        ids = response.json()
        print(f"Fetched {len(ids)} story IDs. Using first {n}.")
        return ids[:n]
    except requests.RequestException as e:
        print(f"Failed to fetch story IDs: {e}")
        return []

# ──────────────────────────────────────────────
# STEP 2: FETCH INDIVIDUAL STORY DETAILS
# ──────────────────────────────────────────────

def fetch_story(story_id):
    """Fetch a single story's details by ID. Returns None on failure."""
    url = f"{BASE_URL}/item/{story_id}.json"
    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        print(f"Failed to fetch story {story_id}: {e}")
        return None

# ──────────────────────────────────────────────
# STEP 3: ASSIGN CATEGORY BASED ON KEYWORDS
# ──────────────────────────────────────────────

def assign_category(title):
    """
    Check the story title against each category's keyword list.
    Returns the first matching category name, or None if no match.
    """
    if not title:
        return None
    title_lower = title.lower()
    for category, keywords in CATEGORIES.items():
        for keyword in keywords:
            if keyword.lower() in title_lower:
                return category
    return None

# ──────────────────────────────────────────────
# STEP 4: EXTRACT REQUIRED FIELDS
# ──────────────────────────────────────────────

def extract_fields(story, category):
    """
    Pull out the 7 required fields from a raw story object.
    'collected_at' is added by us — not from the API.
    """
    return {
        "post_id":      story.get("id"),
        "title":        story.get("title", ""),
        "category":     category,
        "score":        story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author":       story.get("by", ""),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

# ──────────────────────────────────────────────
# MAIN PIPELINE
# ──────────────────────────────────────────────

def main():
    # Fetch top story IDs
    story_ids = fetch_top_story_ids()
    if not story_ids:
        print("No story IDs retrieved. Exiting.")
        return

    # Pre-fetch all stories (avoid re-fetching for each category)
    print("Fetching story details...")
    raw_stories = []
    for sid in story_ids:
        story = fetch_story(sid)
        if story and story.get("type") == "story" and story.get("title"):
            raw_stories.append(story)

    print(f"Successfully fetched {len(raw_stories)} valid stories.")

    # Bucket stories into categories (up to 25 each)
    # One sleep per category loop as required
    categorized = {cat: [] for cat in CATEGORIES}

    for category in CATEGORIES:
        for story in raw_stories:
            if len(categorized[category]) >= MAX_PER_CATEGORY:
                break
            if assign_category(story.get("title", "")) == category:
                categorized[category].append(extract_fields(story, category))

        print(f"  [{category}] → {len(categorized[category])} stories collected")
        time.sleep(2)  # One 2-second pause per category as required

    # Flatten all categories into one list
    all_stories = [story for stories in categorized.values() for story in stories]

    # ──────────────────────────────────────────
    # STEP 5: SAVE TO JSON FILE
    # ──────────────────────────────────────────

    # Create data/ folder if it doesn't exist
    os.makedirs("data", exist_ok=True)

    # File name includes today's date
    date_str = datetime.now().strftime("%Y%m%d")
    output_path = f"data/trends_{date_str}.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(all_stories, f, indent=2, ensure_ascii=False)

    print(f"\nCollected {len(all_stories)} stories. Saved to {output_path}")

# ──────────────────────────────────────────────
# ENTRY POINT
# ──────────────────────────────────────────────

if __name__ == "__main__":
    main()