# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAMv8UrGrnV0B7-4HaubN2df0JPoSFv7
"""

# -----------------------------------------
# TrendPulse — Task 4: Visualization
# -----------------------------------------
# Creates charts from analysed data and saves them as PNG files

import pandas as pd
import matplotlib.pyplot as plt
import os

# -----------------------------------------
# Step 1: Load data & setup
# -----------------------------------------

file_path = "data/trends_analysed.csv"

if not os.path.exists(file_path):
    print("CSV file not found. Run Task 3 first.")
    exit()

df = pd.read_csv(file_path)

# Create outputs folder
os.makedirs("outputs", exist_ok=True)

# -----------------------------------------
# Helper: shorten long titles
# -----------------------------------------

def shorten_title(title, length=50):
    return title[:length] + "..." if len(title) > length else title

# -----------------------------------------
# Chart 1: Top 10 Stories by Score
# -----------------------------------------

top10 = df.sort_values(by="score", ascending=False).head(10)

titles = [shorten_title(t) for t in top10["title"]]

plt.figure()
plt.barh(titles, top10["score"])
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")
plt.gca().invert_yaxis()  # highest on top
plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.close()

# -----------------------------------------
# Chart 2: Stories per Category
# -----------------------------------------

category_counts = df["category"].value_counts()

plt.figure()
plt.bar(category_counts.index, category_counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("outputs/chart2_categories.png")
plt.close()

# -----------------------------------------
# Chart 3: Score vs Comments (Scatter)
# -----------------------------------------

plt.figure()

# Separate popular and non-popular
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png")
plt.close()

# -----------------------------------------
# BONUS: Dashboard (Combined Figure)
# -----------------------------------------

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Chart 1 in dashboard
axes[0].barh(titles, top10["score"])
axes[0].set_title("Top Stories")
axes[0].invert_yaxis()

# Chart 2 in dashboard
axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Categories")
axes[1].tick_params(axis='x', rotation=45)

# Chart 3 in dashboard
axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].legend()

fig.suptitle("TrendPulse Dashboard")
plt.tight_layout()
plt.savefig("outputs/dashboard.png")
plt.close()

print("All charts saved in outputs/ folder.")



