# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f21-gGzNAkp1SQ_zOxSto2lKUo-XZnhX
"""

# -----------------------------------------
# TrendPulse — Task 3: Data Analysis
# -----------------------------------------
# Loads cleaned CSV data and performs
# analysis to extract insights.

import pandas as pd
import os

# -----------------------------------------
# Step 1: Load latest CSV file
# -----------------------------------------

data_folder = "data"

files = [f for f in os.listdir(data_folder) if f.endswith(".csv")]

if not files:
    print("No CSV files found. Run Task 2 first.")
    exit()

latest_file = sorted(files)[-1]
file_path = os.path.join(data_folder, latest_file)

print(f"Loading cleaned data from: {file_path}")

df = pd.read_csv(file_path)

print(f"Total records: {len(df)}")

# -----------------------------------------
# Step 2: Category Distribution
# -----------------------------------------

print("\n📊 Category Distribution:")
category_counts = df["category"].value_counts()
print(category_counts)

# -----------------------------------------
# Step 3: Average Score per Category
# -----------------------------------------

print("\n📈 Average Score per Category:")
avg_scores = df.groupby("category")["score"].mean().round(2)
print(avg_scores)

# -----------------------------------------
# Step 4: Top 5 Most Commented Posts
# -----------------------------------------

print("\n💬 Top 5 Most Commented Posts:")
top_commented = df.sort_values(by="num_comments", ascending=False).head(5)
print(top_commented[["title", "num_comments", "category"]])

# -----------------------------------------
# Step 5: Top 5 Highest Scored Posts
# -----------------------------------------

print("\n🔥 Top 5 Highest Scored Posts:")
top_scored = df.sort_values(by="score", ascending=False).head(5)
print(top_scored[["title", "score", "category"]])

# -----------------------------------------
# Step 6: Most Active Authors
# -----------------------------------------

print("\n👤 Top 5 Most Active Authors:")
top_authors = df["author"].value_counts().head(5)
print(top_authors)